autocry/urls.py
from os.path import join

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('api/', include('rest_framework.urls')),
    path('nimda/', admin.site.urls),
    path('', include('main_app.urls')),
    path('auth/', include('auth_app.urls')),
] + static(settings.MEDIA_URL, document_root=join(settings.MEDIA_ROOT))

main_app/models.py
from django.db import models
from django.utils import timezone
from main_app.validators import year_validator


class Item(models.Model):
    SEDAN = 'sedan'
    HATCHBACK = 'hatchback'
    ESTATE = 'ESTATE'
    MPV = 'mpv'
    SUV = 'suv'
    UNKNOWN = 'unknown'

    ITEM_TYPES = (
        (SEDAN, 'SEDAN'),
        (HATCHBACK, 'HATCHBACK'),
        (ESTATE, 'ESTATE'),
        (MPV, 'MPV'),
        (SUV, 'SUV'),
        (UNKNOWN, 'Unknown'),
    )

    WEB_Image = 'web_image'
    Local_Image = 'local_image'

    IMAGE_TYPES = (
        (WEB_Image, 'WEB Image'),
        (Local_Image, 'Local or No Image'),
    )

    author = models.ForeignKey('auth.User', default=None, on_delete=models.CASCADE)
    type = models.CharField(max_length=9, choices=ITEM_TYPES, default=UNKNOWN)
    make = models.CharField(max_length=15, default='', blank=False)
    model = models.CharField(max_length=20, default='', blank=False)
    build_year = models.IntegerField(validators=[year_validator])
    description = models.TextField(blank=False)
    image_type = models.CharField(max_length=11, choices=IMAGE_TYPES)
    image_url = models.URLField(blank=True,
                                default='https://s.clipartkey.com/mpngs/s/39-392476_transparent-jeep-clipart-audi-a4-2014-front.png')
    image_file = models.ImageField(blank=True, default='../static/img/car.png', upload_to='images')
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()


# Additional property db
class Like(models.Model):
    author = models.ForeignKey('auth.User', default=None, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    # Helper field to make db visible in admin panel, using "manager class"
    # test = models.CharField(max_length=2)


class Comment(models.Model):
    author = models.ForeignKey('auth.User', default=None, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    comment = models.TextField(blank=False, max_length=200)
    published = models.DateField()

    def publish(self):
        self.published = timezone.now()
        self.save()

templates/items/image_delete.html
{% extends 'landing_page.html' %}
{% load static %}
{% block content %}
    <div class="container text-center">
        {% if item.image_url %}
            <div id="image_url_input">
                <img id="web_img_preview"
                     src="{{ item.image_url|default:"https://s.clipartkey.com/mpngs/s/39-392476_transparent-jeep-clipart-audi-a4-2014-front.png" }}"
                     class="w-50 rounded mx-auto d-block" alt="Image goes here!"/>
            </div>
        {% elif item.image_file.url %}
            <div id="image_file_input">
                <img id="local_img_preview" src="{{ item.image_file.url }}" class="w-50 rounded mx-auto d-block"
                     alt="Image goes here!"/>
            </div>
        {% endif %}
    </div>
{% endblock content %}

templates/items/image_upload.html
{% extends 'landing_page.html' %}
{% load static %}
{% block content %}
    <div class="container text-center">
        <form method="post" class="furniture-form" enctype="multipart/form-data">
            <div id="image_url_input">
                <h3 class="text-center">Add new photo from WEB</h3>
                <label for="{{ form.image_url.id_for_label }}">WEB Image Upload</label>
                {{ form.image_url }}
                {{ form.image_url.errors }}
                <img id="web_img_preview"
                     src="{{ item.image_url|default:"https://s.clipartkey.com/mpngs/s/39-392476_transparent-jeep-clipart-audi-a4-2014-front.png" }}"
                     class="w-50 rounded mx-auto d-block" alt="Image goes here!"/>
            </div>
            <div id="image_file_input">
                <h3 class="text-center">Add new photo from Local PC</h3>
                <label for="{{ form.image_file.id_for_label }}">Local Image Upload (Leave it blank for No Image)</label>
                {{ form.image_file }}
                {{ form.image_file.errors }}
                <img id="local_img_preview" src="{{ item.image_file.url }}" class="w-50 rounded mx-auto d-block"
                     alt="Image goes here!"/>
            </div>
            <button id="btn_create" class="btn btn-primary mt-2" type="submit">Upload vehicle</button>
        </form>
    </div>
    <script src="/static/js/image_preview.js"></script>
    <script src="/static/js/local_image_preview.js"></script>
{% endblock content %}

templates/items/item_create.html
{% extends 'landing_page.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <h1 class="text-center">Add new vehicle details</h1>
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <form method="post" class="furniture-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'items/item_no_image_data.html' %}
                    {% include 'items/image_upload.html' %}
                </form>
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div>
{% endblock content %}

templates/items/item_delete.html
{% extends 'landing_page.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h1>Are you sure to delete vehicle {{ item.name }}?</h1>
                <div class="m-auto d-flex justify-content-center">
                    <div class="m-2">
                        <form method="post" action="{% url 'delete item' item.pk %}">
                            {% csrf_token %}
                            {% include 'items/item_no_image_data.html' %}
                            {% include 'items/image_delete.html' %}
                            <input type="submit" value="Confirm" class="btn btn-danger"/>
                            <a class="btn btn-primary" href="javascript:history.back()">No, go back</a>
                        </form>
                    </div>
                    <div class="m-2">
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/items/item_detail.html
{% extends 'landing_page.html' %}
{% load custom_tags %}
{% block content %}
    <div class="container">
        <div class="d-flex">
            <div class="d-inline p-2 w-50">
                {% if item.image_url %}
                    <img src="{{ item.image_url }}" class="w-50 rounded mx-auto d-block"
                         alt="image of {{ item.name }}">
                {% else %}
                    <img src="{{ item.image_file.url }}" class="w-50 rounded mx-auto d-block"
                         alt="image of {{ item.name }}">
                {% endif %}
            </div>
            <div class="d-inline p-2 w-50">
                <div class="d-flex justify-content-between">
                    <ul>
                        <li><h5><em>Type:</em> {{ item.type|capfirst }}</h5></li>
                        <li><h5><em>Make:</em> {{ item.make }}</h5></li>
                        <li><h5><em>Model:</em> {{ item.model }}</h5></li>
                        <li><h5><em>Build year:</em> {{ item.build_year }}</h5></li>
                        <li><h5><em>Author:</em>
                            <a href="{% url 'user profile' item.author_id %}"
                               style="color: red"> {{ users|get_item:item.author_id }}</a></h5></li>
                    </ul>
                </div>
                <p class="mt-2" style="overflow-wrap: break-word;">Description: {{ item.description }}</p>
                <div>
                    {% if item.can_edit %}
                        <a href="{% url 'edit item' item.id %}" class="btn btn-success">Edit</a>
                        <a href="{% url 'delete item' item.id %}" class="btn btn-danger">Delete</a>
                    {% endif %}
                </div>
                <div style="padding-top: 3%">
                    {% if not is_author %}
                        {% if item.can_like %}
                            <a href="{% url 'like item' item.pk %}" style="color: red"><i
                                    class="fa fa-thumbs-down fa-3x"
                                    aria-hidden="true"></i>
                                <em><b>UnLike</b></em></a>
                        {% else %}
                            <a href="{% url 'like item' item.pk %}" style="color: green"><i
                                    class="fa fa-thumbs-up fa-3x"
                                    aria-hidden="true"></i>
                                <em><b>Like</b></em></a>
                        {% endif %}
                    {% endif %}
                </div>
                <p class="mt-2"><u>Fellow Users' Likes:</u> <span style="font-size: x-large; color: red;"><b>&nbsp;&nbsp;{{ item.like_set.count }}</b></span>
                </p>
            </div>
        </div>
    </div>
    <div class="d-block inner_body" style="background-color: #f1e3e3; padding:2%" id="accordion">
        <div class="inner_head text-right">
            <button class="btn btn-primary mt-2" type="submit" id="more_less_btn" onclick="toggle_comment()">Hide comments</button>
        </div>
        <div id="extra" style="display: block">
            <div class="box">
                <form method="post" action="{% url 'item details or comment' item.pk %}">
                    {% csrf_token %}
                    {{ form }}
                    <button class="btn btn-primary mt-2" type="submit">Add comment</button>
                </form>
            </div>
            {% if item.comment_set.count > 0 %}
                <div class="box">
                    <hr>
                    <h4 class="text-lg-center" style="color: #6f42c1"><u>Users' comments uploaded:</u></h4>
                    <hr>
                </div>
                {% for comment in item.comment_set.all %}
                    <div class="box">
                        {# Used instead of custom template tag #}
                        {#                                        {% for key, value in users.items %}#}
                        {#                        {% if key == comment.author_id %}#}
                        <h5><em><u>Written by &nbsp;<a onclick="comments()">
                            <span style="color: red" id="refer_to">"{{ users|get_item:comment.author_id }}"</span></a>
                            &nbsp;on {{ comment.published }}:</u></em></h5>
                        {#                        {% endif %}#}
                        {#                    {% endfor %}#}
                        <h5>{{ comment.comment }}</h5>
                        <hr>
                    </div>
                {% endfor %}
            {% else %}
                <div class="box">
                    <h3>There are no comments for this item. </h3>
                </div>
            {% endif %}
        </div>
    </div>
    <script src="/static/js/comments.js"></script>
{% endblock content %}

templates/items/item_edit.html
{% extends 'landing_page.html' %}

{% block content %}
    <div class="container">
        <h1 class="text-center">Edit vehicle entry</h1>
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <form method="post" class="furniture-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'items/item_no_image_data.html' %}
                    {% include 'items/image_upload.html' %}
                </form>
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div>
{% endblock content %}

templates/items/item_list.html
{% extends 'landing_page.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="container">
        <h1 class='text-center'>All vehicles</h1>
        {% include 'common/items.html' %}
    </div>
{% endblock content %}

templates/items/item_no_image_data.html
{% if form %}
    <label for="{{ form.type.id_for_label }}">Vehicle Type</label>
    {{ form.type }}
    {{ form.type.errors }}

    <label for="{{ form.make.id_for_label }}">Vehicle Make</label>
    {{ form.make }}
    {{ form.make.errors }}

    <label for="{{ form.model.id_for_label }}">Vehicle Model</label>
    {{ form.model }}
    {{ form.model.errors }}

    <label for="{{ form.build_year.id_for_label }}">Build Year</label>
    {{ form.build_year }}
    {{ form.build_year.errors }}

    <label for="{{ form.description.id_for_label }}">Description</label>
    {{ form.description }}
    {{ form.description.errors }}

    <label for="{{ form.image_type.id_for_label }}">Image Type Upload</label>
    {{ form.image_type }}
    {{ form.image_type.errors }}
    {{ input_type }}
{% else %}
    {{ form }}
{% endif %}